"""Vouchstone Python SDK — Build Accountable AI Agents with 5-Layer Memory"""

from .client import VouchstoneClient
from .vault import VaultClient
from .agent import Agent, AgentConfig
from .memory import (
    WorkingMemory,
    EpisodicMemory,
    SemanticMemory,
    ProceduralMemory,
    MetaMemory,
    MemoryPipeline,
)
from .graph import (
    EntityGraph,
    Edge,
    PolicyGraph,
    Policy,
    PolicyDecision,
    WorkflowTrace,
    WorkflowTraceEntry,
    canonical_json,
    compute_entry_hash,
)
from .forge import (
    Forge,
    ForgeResult,
    EngineAdapter,
    ClaudeEngineAdapter,
    EchoEngineAdapter,
    Diff,
    FileChange,
    CompatibilityGate,
    GateResult,
    SandboxRunner,
    SubprocessSandboxRunner,
    SandboxResult,
)
from .transform import (
    TemplateParameter,
    TransformationTemplate,
    TemplateLibrary,
    TemplateEngineAdapter,
    TemplateNotMatchedError,
    MissingTemplateParametersError,
    ReplayResult,
    replay_and_verify,
    default_template_library,
)
from .telemetry import (
    configure_telemetry,
    get_tracer,
    is_otel_available,
    span,
    record_exception,
)
from .eval import (
    EvalCase,
    EvalSuite,
    EvalReport,
    EvalCaseResult,
    GradeResult,
    default_grader,
    run_eval_suite,
)
from .plugins import (
    PluginRegistry,
    PluginLoadError,
    ENGINE_ADAPTERS,
    EXTRACTION_STRATEGIES,
    EVAL_GRADERS,
)
from .types import (
    Message,
    Decision,
    AgentResponse,
    MemoryEntry,
    Episode,
    EpisodicTrace,
    Entity,
    Skill,
    MemoryContext,
    TurnResult,
    HealthReport,
    AgentDefinition,
    AgentStatus,
    MemoryLayer,
)

from . import ingestion

__version__ = "1.4.0"
__all__ = [
    "ingestion",
    "VouchstoneClient",
    "VaultClient",
    "Agent",
    "AgentConfig",
    "WorkingMemory",
    "EpisodicMemory",
    "SemanticMemory",
    "ProceduralMemory",
    "MetaMemory",
    "MemoryPipeline",
    "EntityGraph",
    "Edge",
    "PolicyGraph",
    "Policy",
    "PolicyDecision",
    "WorkflowTrace",
    "WorkflowTraceEntry",
    "canonical_json",
    "compute_entry_hash",
    "Forge",
    "ForgeResult",
    "EngineAdapter",
    "ClaudeEngineAdapter",
    "EchoEngineAdapter",
    "Diff",
    "FileChange",
    "CompatibilityGate",
    "GateResult",
    "SandboxRunner",
    "SubprocessSandboxRunner",
    "SandboxResult",
    "TemplateParameter",
    "TransformationTemplate",
    "TemplateLibrary",
    "TemplateEngineAdapter",
    "TemplateNotMatchedError",
    "MissingTemplateParametersError",
    "ReplayResult",
    "replay_and_verify",
    "default_template_library",
    "configure_telemetry",
    "get_tracer",
    "is_otel_available",
    "span",
    "record_exception",
    "EvalCase",
    "EvalSuite",
    "EvalReport",
    "EvalCaseResult",
    "GradeResult",
    "default_grader",
    "run_eval_suite",
    "PluginRegistry",
    "PluginLoadError",
    "ENGINE_ADAPTERS",
    "EXTRACTION_STRATEGIES",
    "EVAL_GRADERS",
    "Message",
    "Decision",
    "AgentResponse",
    "MemoryEntry",
    "Episode",
    "EpisodicTrace",
    "Entity",
    "Skill",
    "MemoryContext",
    "TurnResult",
    "HealthReport",
    "AgentDefinition",
    "AgentStatus",
    "MemoryLayer",
]
